name: lesson3_ci
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: env_prepare
        run: |
          pwd
          ls -l
          python -m pip install -r ./requirements_ci.txt
      - name: tests_do
        run: |
          cd ./src
          python -m pytest .. -v
